prooph_event_store:
    stores:
        default:
            event_store: 'Prooph\EventStore\EventStore'

services:
    App\EventStore\PersistenceStrategy\StreamStrategy: ~

    App\EventSourcing\Aggregate\AggregateTranslator: ~
