services:
    Prooph\EventStoreBusBridge\EventPublisher:
        arguments:
            - '@prooph_service_bus.default_event_bus'
        tags:
            - { name: 'prooph_event_store.default.plugin' }

    Prooph\EventStoreBusBridge\TransactionManager:
        arguments:
            - '@Prooph\EventStore\EventStore'
        tags:
            - { name: 'prooph_service_bus.default_command_bus.plugin' }
