twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        js_data: '@App\DataProvider\JsData'
        ga_tracking_id: '%env(GA_TRACKING_ID)%'
        # needed because it's used in the menu to generate the link to the previous user filters
#        user_filter:    '@xm_user_admin.filter.user'
        form_themes:
            - 'Form/fields.html.twig'
#            - 'VichUploaderBundle:Form:fields.html.twig'
