admin_dashboard:
    path: /admin
    defaults:
        _controller: TemplateController:template
        template:    static/admin_dashboard.html.twig
        # this is very short because the page has link that may change
        maxAge:      60
        # 1 hour
        sharedAge:   3600
